[platformio]
default_envs = esp32c3_supermini

[env:esp32c3_supermini]
platform = espressif32@7.0.1
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.embed_files = data/cert/x509_crt_bundle.bin
extra_scripts = pre:scripts/pio_prebuild.py
lib_deps =
  https://github.com/olikraus/U8g2_Arduino.git#c58449414f7d9f72881af165e2fccac606fce7da
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
build_src_filter =
  +<main.cpp>
  -<oled_smoke.cpp>
  -<key_smoke.cpp>

[env:oled_smoke]
extends = env:esp32c3_supermini
lib_deps =
  U8g2=file://.pio/libdeps/esp32c3_supermini/U8g2
build_src_filter =
  -<main.cpp>
  +<oled_smoke.cpp>
  -<key_smoke.cpp>

[env:key_smoke]
extends = env:esp32c3_supermini
lib_deps =
  U8g2=file://.pio/libdeps/esp32c3_supermini/U8g2
build_src_filter =
  -<main.cpp>
  -<oled_smoke.cpp>
  +<key_smoke.cpp>
